import { Countries } from 'src/app/models/county-model';

export var countries: Countries [] = [
    { code: "AF", name: "Afghanistan", number: "093", value: "93", flag: "af.svg" },
    { code: "AL", name: "Albania", number: "355", value: "355", flag: "al.svg" },
    { code: "DZ", name: "Algeria", number: "213", value: "213", flag: "dz.svg" },
    { code: "AS", name: "American Samoa", number: "001", value: "1", flag: "as.svg" },
    { code: "AD", name: "Andorra", number: "376", value: "376", flag: "ad.svg" },
    { code: "AO", name: "Angola", number: "244", value: "244", flag: "ao.svg" },
    { code: "AI", name: "Anguilla", number: "001", value: "1", flag: "ai.svg" },
    { code: "AG", name: "Antigua and Barbuda", number: "001", value: "1", flag: "ag.svg" },
    { code: "AR", name: "Argentina", number: "054", value: "54", flag: "ar.svg" },
    { code: "AM", name: "Armenia", number: "374", value: "374", flag: "am.svg" },
    { code: "AW", name: "Aruba", number: "294", value: "294", flag: "aw.svg" },
    { code: "AU", name: "Australia", number: "061", value: "61", flag: "au.svg" },
    { code: "AT", name: "Austria", number: "043", value: "43", flag: "at.svg" },
    { code: "AZ", name: "Azerbaijan", number: "994", value: "994", flag: "az.svg" },
    { code: "BS", name: "Bahamas", number: "001", value: "1", flag: "bs.svg" },
    { code: "BH", name: "Bahrain", number: "973", value: "973", flag: "bh.svg" },
    { code: "BD", name: "Bangladesh", number: "880", value: "880", flag: "bd.svg" },
    { code: "BB", name: "Barbados", number: "001", value: "1", flag: "bb.svg" },
    { code: "BY", name: "Belarus", number: "375", value: "375", flag: "by.svg" },
    { code: "BE", name: "Belgium", number: "032", value: "32", flag: "be.svg" },
    { code: "BZ", name: "Belize", number: "501", value: "501", flag: "bz.svg" },
    { code: "BJ", name: "Benin", number: "229", value: "229", flag: "bj.svg" },
    { code: "BM", name: "Bermuda", number: "001", value: "1", flag: "bm.svg" },
    { code: "BT", name: "Bhutan", number: "975", value: "975", flag: "bt.svg" },
    { code: "BO", name: "Bolivia", number: "591", value: "591", flag: "bo.svg" },
    { code: "BA", name: "Bosnia and Herzegovina", number: "387", value: "387", flag: "ba.svg" },
    { code: "BW", name: "Botswana", number: "267", value: "267", flag: "bw.svg" },
    { code: "BR", name: "Brazil (Brasil)", number: "055", value: "55", flag: "br.svg" },
    { code: "IO", name: "British Indian Ocean Territory", number: "246", value: "246", flag: "io.svg" },
    { code: "BN", name: "Brunei Darussalam", number: "673", value: "673", flag: "bn.svg" },
    { code: "BG", name: "Bulgaria", number: "359", value: "359", flag: "bg.svg" },
    { code: "BF", name: "Burkina Faso", number: "226", value: "226", flag: "bf.svg" },
    { code: "BI", name: "Burundi", number: "257", value: "257", flag: "bi.svg" },
    { code: "CV", name: "Cabo Verde", number: "238", value: "238", flag: "cv.svg" },
    { code: "KH", name: "Cambodia", number: "855", value: "855", flag: "kh.svg" },
    { code: "CM", name: "Cameroon", number: "237", value: "237", flag: "cm.svg" },
    { code: "CA", name: "Canada", number: "001", value: "1", flag: "ca.svg" },
    { code: "NL", name: "Caribbean Netherlands", number: "599", value: "599", flag: "nl.svg" },
    { code: "KY", name: "Cayman Islands", number: "001", value: "1", flag: "ky.svg" },
    { code: "CF", name: "Central African Republic", number: "236", value: "236", flag: "cf.svg" },
    { code: "TD", name: "Chad", number: "235", value: "235", flag: "td.svg" },
    { code: "CL", name: "Chile", number: "056", value: "56", flag: "cl.svg" },
    { code: "CN", name: "China", number: "086", value: "86", flag: "cn.svg" },
    { code: "CX", name: "Christmas Island", number: "061", value: "61", flag: "cx.svg" },
    { code: "CC", name: "Cocos (Keeling) Islands", number: "061", value: "61", flag: "cc.svg" },
    { code: "CO", name: "Colombia", number: "057", value: "57", flag: "co.svg" },
    { code: "KM", name: "Comoros (the)", number: "269", value: "269", flag: "km.svg" },
    { code: "CD", name: "Congo (the Democratic Republic of the)", number: "243", value: "243", flag: "cd.svg" },
    { code: "CG", name: "Congo (Republic of the)", number: "242", value: "242", flag: "cg.svg" },
    { code: "CK", name: "Cook Islands (the)", number: "682", value: "682", flag: "ck.svg" },
    { code: "CR", name: "Costa Rica", number: "506", value: "506", flag: "cr.svg" },
    { code: "HR", name: "Croatia", number: "385", value: "385", flag: "hr.svg" },
    { code: "CU", name: "Cuba", number: "053", value: "53", flag: "cu.svg" },
    { code: "CW", name: "Curaçao", number: "599", value: "599", flag: "cw.svg" },
    { code: "CY", name: "Cyprus", number: "357", value: "357", flag: "cy.svg" },
    { code: "CZ", name: "Czech Republic", number: "420", value: "420", flag: "cz.svg" },
    { code: "CI", name: "Côte d'Ivoire", number: "225", value: "225", flag: "ci.svg" },
    { code: "DK", name: "Denmark", number: "045", value: "45", flag: "dk.svg" },
    { code: "DJ", name: "Djibouti", number: "253", value: "253", flag: "dj.svg" },
    { code: "DM", name: "Dominica", number: "001", value: "1", flag: "dm.svg" },
    { code: "DO", name: "Dominican Republic (the)", number: "001", value: "1", flag: "do.svg" },
    { code: "EC", name: "Ecuador", number: "593", value: "593", flag: "ec.svg" },
    { code: "EG", name: "Egypt", number: "020", value: "20", flag: "eg.svg" },
    { code: "SV", name: "El Salvador", number: "503", value: "503", flag: "sv.svg" },
    { code: "GQ", name: "Equatorial Guinea", number: "240", value: "240", flag: "gq.svg" },
    { code: "ER", name: "Eritrea", number: "291", value: "291", flag: "er.svg" },
    { code: "EE", name: "Estonia", number: "372", value: "372", flag: "ee.svg" },
    { code: "SZ", name: "Eswatini", number: "268", value: "268", flag: "sz.svg" },
    { code: "ET", name: "Ethiopia", number: "251", value: "251", flag: "et.svg" },
    { code: "FK", name: "Falkland Islands (the Malvinas)", number: "500", value: "500", flag: "fk.svg" },
    { code: "FO", name: "Faroe Islands", number: "298", value: "298", flag: "fo.svg" },
    { code: "FJ", name: "Fiji", number: "679", value: "679", flag: "fj.svg" },
    { code: "FI", name: "Finland", number: "358", value: "358", flag: "fi.svg" },
    { code: "FR", name: "France", number: "033", value: "33", flag: "fr.svg" },
    { code: "GF", name: "French Guiana", number: "594", value: "594", flag: "gf.svg" },
    { code: "PF", name: "French Polynesia", number: "689", value: "689", flag: "pf.svg" },
    { code: "GA", name: "Gabon", number: "241", value: "241", flag: "ga.svg" },
    { code: "GM", name: "Gambia", number: "220", value: "220", flag: "gm.svg" },
    { code: "GE", name: "Georgia", number: "995", value: "995", flag: "ge.svg" },
    { code: "DE", name: "Germany", number: "049", value: "49", flag: "de.svg" },
    { code: "GH", name: "Ghana", number: "233", value: "233", flag: "gh.svg" },
    { code: "GI", name: "Gibraltar", number: "350", value: "350", flag: "gi.svg" },
    { code: "GR", name: "Greece", number: "030", value: "30", flag: "gr.svg" },
    { code: "GL", name: "Greenland", number: "299", value: "299", flag: "gl.svg" },
    { code: "GD", name: "Grenada", number: "001", value: "1", flag: "gd.svg" },
    { code: "GP", name: "Guadeloupe", number: "590", value: "590", flag: "gp.svg" },
    { code: "GU", name: "Guam", number: "001", value: "1", flag: "gu.svg" },
    { code: "GT", name: "Guatemala", number: "502", value: "502", flag: "gt.svg" },
    { code: "GG", name: "Guernsey", number: "044", value: "44", flag: "gg.svg" },
    { code: "GN", name: "Guinea", number: "224", value: "224", flag: "gn.svg" },
    { code: "GW", name: "Guinea-Bissau", number: "245", value: "245", flag: "gw.svg" },
    { code: "GY", name: "Guyana", number: "592", value: "592", flag: "gy.svg" },
    { code: "HT", name: "Haiti", number: "509", value: "509", flag: "ht.svg" },
    { code: "HN", name: "Honduras", number: "504", value: "504", flag: "hn.svg" },
    { code: "HK", name: "Hong Kong", number: "852", value: "852", flag: "hk.svg" },
    { code: "HU", name: "Hungary", number: "036", value: "36", flag: "hu.svg" },
    { code: "IS", name: "Iceland", number: "354", value: "354", flag: "is.svg" },
    { code: "IN", name: "India", number: "091", value: "91", flag: "in.svg" },
    { code: "ID", name: "Indonesia", number: "062", value: "62", flag: "id.svg" },
    { code: "IR", name: "Iran (Islamic Republic of)", number: "098", value: "98", flag: "ir.svg" },
    { code: "IQ", name: "Iraq", number: "964", value: "964", flag: "iq.svg" },
    { code: "IE", name: "Ireland", number: "353", value: "353", flag: "ie.svg" },
    { code: "IM", name: "Isle of Man", number: "044", value: "44", flag: "im.svg" },
    { code: "IL", name: "Israel", number: "972", value: "972", flag: "il.svg" },
    { code: "IT", name: "Italy", number: "039", value: "39", flag: "it.svg" },
    { code: "JM", name: "Jamaica", number: "001", value: "1", flag: "jm.svg" },
    { code: "JP", name: "Japan", number: "081", value: "81", flag: "jp.svg" },
    { code: "JE", name: "Jersey", number: "044", value: "44", flag: "je.svg" },
    { code: "JO", name: "Jordan", number: "962", value: "962", flag: "jo.svg" },
    { code: "KZ", name: "Kazakhstan", number: "007", value: "7", flag: "kz.svg" },
    { code: "KE", name: "Kenya", number: "254", value: "254", flag: "ke.svg" },
    { code: "KI", name: "Kiribati", number: "686", value: "686", flag: "ki.svg" },
    { code: "KV", name: "Kosovo", number: "383", value: "383", flag: "kv.svg" },
    { code: "KW", name: "Kuwait", number: "965", value: "965", flag: "kw.svg" },
    { code: "KG", name: "Kyrgyzstan", number: "996", value: "996", flag: "kg.svg" },
    { code: "LA", name: "Laos (People's Democratic Republic)", number: "856", value: "856", flag: "la.svg" },
    { code: "LV", name: "Latvia", number: "371", value: "371", flag: "lv.svg" },
    { code: "LB", name: "Lebanon", number: "961", value: "961", flag: "lb.svg" },
    { code: "LS", name: "Lesotho", number: "266", value: "266", flag: "ls.svg" },
    { code: "LR", name: "Liberia", number: "231", value: "231", flag: "lr.svg" },
    { code: "LY", name: "Libya", number: "218", value: "218", flag: "ly.svg" },
    { code: "LI", name: "Liechtenstein", number: "423", value: "423", flag: "li.svg" },
    { code: "LT", name: "Lithuania", number: "370", value: "370", flag: "lt.svg" },
    { code: "LU", name: "Luxembourg", number: "352", value: "352", flag: "lu.svg" },
    { code: "MO", name: "Macao", number: "853", value: "853", flag: "mo.svg" },
    { code: "MK", name: "Macedonia", number: "389", value: "389", flag: "mk.svg" },
    { code: "MG", name: "Madagascar", number: "231", value: "231", flag: "mg.svg" },
    { code: "MW", name: "Malawi", number: "265", value: "265", flag: "mw.svg" },
    { code: "MY", name: "Malaysia", number: "060", value: "60", flag: "my.svg" },
    { code: "MV", name: "Maldives", number: "960", value: "960", flag: "mv.svg" },
    { code: "ML", name: "Mali", number: "223", value: "223", flag: "ml.svg" },
    { code: "MT", name: "Malta", number: "356", value: "356", flag: "mt.svg" },
    { code: "MH", name: "Marshall Islands", number: "692", value: "692", flag: "mh.svg" },
    { code: "MQ", name: "Martinique", number: "596", value: "596", flag: "mq.svg" },
    { code: "MR", name: "Mauritania", number: "222", value: "222", flag: "mr.svg" },
    { code: "MU", name: "Mauritius (Moris)", number: "230", value: "230", flag: "mu.svg" },
    { code: "YT", name: "Mayotte", number: "262", value: "262", flag: "yt.svg" },
    { code: "MX", name: "México", number: "052", value: "52", flag: "mx.svg" },
    { code: "FM", name: "Micronesia", number: "691", value: "691", flag: "fm.svg" },
    { code: "MD", name: "Moldova (the Republic of)", number: "373", value: "373", flag: "md.svg" },
    { code: "MC", name: "Monaco", number: "377", value: "377", flag: "mc.svg" },
    { code: "MN", name: "Mongolia", number: "976", value: "976", flag: "mn.svg" },
    { code: "ME", name: "Montenegro", number: "382", value: "382", flag: "me.svg" },
    { code: "MS", name: "Montserrat", number: "001", value: "1", flag: "ms.svg" },
    { code: "MA", name: "Morocco", number: "212", value: "212", flag: "ma.svg" },
    { code: "MZ", name: "Mozambique", number: "258", value: "258", flag: "mz.svg" },
    { code: "MM", name: "Myanmar", number: "095", value: "95", flag: "mm.svg" },
    { code: "NA", name: "Namibia", number: "264", value: "264", flag: "na.svg" },
    { code: "NR", name: "Nauru", number: "674", value: "674", flag: "nr.svg" },
    { code: "NP", name: "Nepal", number: "977", value: "977", flag: "np.svg" },
    { code: "NL", name: "Netherlands", number: "031", value: "31", flag: "nl.svg" },
    { code: "NC", name: "New Caledonia", number: "687", value: "687", flag: "nc.svg" },
    { code: "NZ", name: "New Zealand", number: "064", value: "64", flag: "nz.svg" },
    { code: "NI", name: "Nicaragua", number: "505", value: "505", flag: "ni.svg" },
    { code: "NE", name: "Niger", number: "224", value: "224", flag: "ne.svg" },
    { code: "NG", name: "Nigeria", number: "234", value: "234", flag: "ng.svg" },
    { code: "NU", name: "Niue", number: "683", value: "683", flag: "nu.svg" },
    { code: "NF", name: "Norfolk Island", number: "672", value: "672", flag: "nf.svg" },
    { code: "KP", name: "North Korea", number: "850", value: "850", flag: "kp.svg" },
    { code: "MP", name: "Northern Mariana Islands", number: "001", value: "1", flag: "mp.svg" },
    { code: "NO", name: "Norway", number: "047", value: "47", flag: "no.svg" },
    { code: "OM", name: "Oman", number: "968", value: "968", flag: "om.svg" },
    { code: "PK", name: "Pakistan", number: "092", value: "92", flag: "pk.svg" },
    { code: "PW", name: "Palau", number: "680", value: "680", flag: "pw.svg" },
    { code: "PS", name: "Palestine", number: "970", value: "970", flag: "ps.svg" },
    { code: "PA", name: "Panama", number: "507", value: "507", flag: "pa.svg" },
    { code: "PG", name: "Papua New Guinea", number: "675", value: "675", flag: "pg.svg" },
    { code: "PY", name: "Paraguay", number: "595", value: "595", flag: "py.svg" },
    { code: "PE", name: "Peru", number: "051", value: "51", flag: "pe.svg" },
    { code: "PH", name: "Philippines", number: "063", value: "63", flag: "ph.svg" },
    { code: "PL", name: "Poland", number: "048", value: "48", flag: "pl.svg" },
    { code: "PT", name: "Portugal", number: "351", value: "351", flag: "pt.svg" },
    { code: "PR", name: "Puerto Rico", number: "001", value: "1", flag: "pr.svg" },
    { code: "QA", name: "Qatar", number: "974", value: "974", flag: "qa.svg" },
    { code: "RE", name: "Réunion", number: "262", value: "262", flag: "re.svg" },
    { code: "RO", name: "Romania", number: "040", value: "40", flag: "ro.svg" },
    { code: "RU", name: "Russia", number: "007", value: "7", flag: "ru.svg" },
    { code: "RW", name: "Rwanda", number: "250", value: "250", flag: "rw.svg" },
    { code: "BL", name: "Saint Barthélemy", number: "590", value: "590", flag: "bl.svg" },
    { code: "SH", name: "Saint Helena", number: "290", value: "290", flag: "sh.svg" },
    { code: "KN", name: "Saint Kitts and Nevis", number: "001", value: "1", flag: "kn.svg" },
    { code: "LC", name: "Saint Lucia", number: "001", value: "1", flag: "lc.svg" },
    { code: "MF", name: "Saint Martin (French part)", number: "590", value: "590", flag: "mf.svg" },
    { code: "PM", name: "Saint Pierre and Miquelon", number: "508", value: "508", flag: "pm.svg" },
    { code: "VC", name: "Saint Vincent and the Grenadines", number: "001", value: "1", flag: "vc.svg" },
    { code: "WS", name: "Samoa", number: "685", value: "685", flag: "ws.svg" },
    { code: "SM", name: "San Marino", number: "378", value: "378", flag: "sm.svg" },
    { code: "ST", name: "São Tome and Príncipe", number: "239", value: "239", flag: "st.svg" },
    { code: "SA", name: "Saudi Arabia", number: "966", value: "966", flag: "sa.svg" },
    { code: "SN", name: "Senegal", number: "221", value: "221", flag: "sn.svg" },
    { code: "RS", name: "Serbia", number: "381", value: "381", flag: "rs.svg" },
    { code: "SC", name: "Seychelles", number: "248", value: "248", flag: "sc.svg" },
    { code: "SL", name: "Sierra Leone", number: "232", value: "232", flag: "sl.svg" },
    { code: "SG", name: "Singapore", number: "065", value: "65", flag: "sg.svg" },
    { code: "SX", name: "Sint Maarten (Dutch part)", number: "001", value: "1", flag: "sx.svg" },
    { code: "SK", name: "Slovakia", number: "421", value: "421", flag: "sk.svg" },
    { code: "SI", name: "Slovenia", number: "386", value: "386", flag: "si.svg" },
    { code: "SB", name: "Solomon Islands", number: "677", value: "677", flag: "sb.svg" },
    { code: "SO", name: "Somalia", number: "252", value: "252", flag: "so.svg" },
    { code: "ZA", name: "South Africa", number: "027", value: "27", flag: "za.svg" },
    { code: "KR", name: "South Korea", number: "082", value: "82", flag: "kr.svg" },
    { code: "SS", name: "South Sudan", number: "211", value: "211", flag: "ss.svg" },
    { code: "ES", name: "Spain", number: "034", value: "34", flag: "es.svg" },
    { code: "LK", name: "Sri Lanka", number: "094", value: "94", flag: "lk.svg" },
    { code: "SD", name: "Sudan", number: "249", value: "249", flag: "sd.svg" },
    { code: "SR", name: "Suriname", number: "597", value: "597", flag: "sr.svg" },
    { code: "SJ", name: "Svalbard and Jan Mayen", number: "047", value: "47", flag: "sj.svg" },
    { code: "SE", name: "Sweden", number: "046", value: "46", flag: "se.svg" },
    { code: "CH", name: "Switzerland", number: "041", value: "41", flag: "ch.svg" },
    { code: "SY", name: "Syria", number: "963", value: "963", flag: "sy.svg" },
    { code: "TW", name: "Taiwan", number: "886", value: "886", flag: "tw.svg" },
    { code: "TJ", name: "Tajikistan", number: "992", value: "992", flag: "tj.svg" },
    { code: "TZ", name: "Tanzania", number: "255", value: "255", flag: "tz.svg" },
    { code: "TH", name: "Thailand", number: "066", value: "66", flag: "th.svg" },
    { code: "TL", name: "Timor-Leste", number: "670", value: "670", flag: "tl.svg" },
    { code: "TG", name: "Togo", number: "220", value: "220", flag: "tg.svg" },
    { code: "TK", name: "Tokelau", number: "690", value: "690", flag: "tk.svg" },
    { code: "TO", name: "Tonga", number: "676", value: "676", flag: "to.svg" },
    { code: "TT", name: "Trinidad and Tobago", number: "001", value: "1", flag: "tt.svg" },
    { code: "TN", name: "Tunisia", number: "216", value: "216", flag: "tn.svg" },
    { code: "TR", name: "Turkey", number: "090", value: "90", flag: "tr.svg" },
    { code: "TM", name: "Turkmenistan", number: "993", value: "993", flag: "tm.svg" },
    { code: "TC", name: "Turks and Caicos Islands", number: "001", value: "1", flag: "tc.svg" },
    { code: "TV", name: "Tuvalu", number: "688", value: "688", flag: "tv.svg" },
    { code: "UG", name: "Uganda", number: "256", value: "256", flag: "ug.svg" },
    { code: "UA", name: "Ukraine", number: "380", value: "380", flag: "ua.svg" },
    { code: "AE", name: "United Arab Emirates", number: "971", value: "971", flag: "ae.svg" },
    { code: "GB", name: "United Kingdom", number: "044", value: "44", flag: "gb.svg" },
    { code: "US", name: "United States of America", number: "001", value: "1", flag: "us.svg" },
    { code: "UY", name: "Uruguay", number: "598", value: "598", flag: "uy.svg" },
    { code: "UZ", name: "Uzbekistan", number: "998", value: "998", flag: "uz.svg" },
    { code: "VU", name: "Vanuatu", number: "678", value: "678", flag: "vu.svg" },
    { code: "VA", name: "Vatican (City)", number: "039", value: "39", flag: "va.svg" },
    { code: "VE", name: "Venezuela", number: "058", value: "58", flag: "ve.svg" },
    { code: "VN", name: "Vietnam ", number: "084", value: "84", flag: "vn.svg" },
    { code: "WF", name: "Wallis and Futuna", number: "681", value: "681", flag: "wf.svg" },
    { code: "EH", name: "Western Sahara", number: "212", value: "212", flag: "eh.svg" },
    { code: "YE", name: "Yemen", number: "967", value: "967", flag: "ye.svg" },
    { code: "ZM", name: "Zambia", number: "260", value: "260", flag: "zm.svg" },
    { code: "ZW", name: "Zimbabwe", number: "263", value: "263", flag: "zw.svg" },
    { code: "AX", name: "Åland Islands", number: "358", value: "358", flag: "ax.svg" }
];